version: '3'
services:
  app:
    container_name: go_rest_skeleton
    build: .
    ports:
      - 8888:8888
#    env_file:
#      - .env
    environment:
      - APP_ENV=${APP_ENV}
      - APP_PORT=${APP_PORT}
      - APP_LANG=${APP_LANG}
      - APP_TIMEZONE=${APP_TIMEZONE}
      - DB_DRIVER=${DB_DRIVER}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DB=${REDIS_DB}
      - TEST_REDIS_HOST=${TEST_REDIS_HOST}
      - TEST_REDIS_PORT=${TEST_REDIS_PORT}
      - TEST_REDIS_PASSWORD=${TEST_REDIS_PASSWORD}
      - TEST_REDIS_DB=${TEST_REDIS_DB}
      - MINIO_HOST=${MINIO_HOST}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - MINIO_BUCKET=${MINIO_BUCKET}
      - ENABLE_REQUEST_ID=${ENABLE_REQUEST_ID}
      - ENABLE_LOGGER=${ENABLE_LOGGER}
      - ENABLE_CORS=${ENABLE_CORS}
      - APP_PRIVATE_KEY=${APP_PRIVATE_KEY}
      - APP_PUBLIC_KEY=${APP_PUBLIC_KEY}
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - mysql_container
      - redis_container
    networks:
      - network_service

  mysql_container:
    image: mysql:5.6
    container_name: mysql_service
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_HOST=${DB_HOST}
      - MYSQL_ROOT_PORT=${DB_PORT}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    networks:
      - network_service
    expose:
      - 3306

  redis_container:
    image: redis
    container_name: redis_service
    ports:
      - 6379:6379
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    networks:
      - network_service
    expose:
      - 6379

  minio_container:
    image: 'bitnami/minio:latest'
    container_name: minio_service
    ports:
      - 9000:9000
    environment:
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - MINIO_DEFAULT_BUCKETS=${MINIO_BUCKET}
    networks:
      - network_service

  adminer_container:
    image: adminer:latest
    container_name: adminer
    environment:
      ADMINER_DEFAULT_SERVER: mysql_container
    ports:
      - 8080:8080

volumes:
  api:

networks:
  network_service:
    driver: bridge
